<script lang="ts">
  import { onMount } from 'svelte';
  import { browserSupabase } from '$lib/client';
  import { ShieldCheck, Smartphone, LockKeyhole } from 'lucide-svelte';
  let { data } = $props();
  let factorId = $state(''); let qr = $state(''); let secret = $state(''); let code = $state(''); let active = $state(false);
  let message = $state(''); let busy = $state(false); let enrolled = $state(false); let pending = $state(false);
  onMount(async () => {
    active=data.aal2;
    const client=browserSupabase(); if (!client) return;
    const {data: factors,error}=await client.auth.mfa.listFactors();
    if(error){message=error.message;return;}
    const verified=factors?.totp?.[0];
    const unfinished=factors?.all?.find(f=>f.factor_type==='totp' && f.status==='unverified');
    factorId=verified?.id ?? unfinished?.id ?? '';
    enrolled=!!verified;
    pending=!!unfinished && !verified;
  });
  async function setup() { const client=browserSupabase(); if (!client || factorId) return; busy=true; message=''; const {data: factor,error}=await client.auth.mfa.enroll({factorType:'totp',friendlyName:'CitaCloud'}); busy=false; if(error){message=error.message;return;} factorId=factor.id; pending=true; qr=factor.totp.qr_code; secret=factor.totp.secret; }
  async function resetPending() { const client=browserSupabase(); if(!client || !pending || !factorId) return; busy=true; const {error}=await client.auth.mfa.unenroll({factorId}); busy=false; if(error){message=error.message;return;} factorId=''; qr=''; secret=''; pending=false; message='Configuración anterior eliminada. Genera un nuevo QR y escanéalo.'; }
  async function verify() { const client=browserSupabase(); if(!client || !factorId) return; const cleanCode=code.replace(/\D/g,''); if(cleanCode.length!==6){message='Escribe los 6 números del código, sin letras.';return;} busy=true; message=''; const {data: challenge,error: challengeError}=await client.auth.mfa.challenge({factorId}); if(challengeError){busy=false;message=challengeError.message;return;} const {error}=await client.auth.mfa.verify({factorId,challengeId:challenge.id,code:cleanCode}); busy=false; if(error){message='Código incorrecto o vencido. Inténtalo otra vez.';return;} active=true; enrolled=true; qr=''; secret=''; code=''; message='Segundo factor verificado. Ya puedes entrar a las secciones protegidas.'; window.location.reload(); }
</script>
<svelte:head><title>Seguridad · CitaCloud</title></svelte:head>
<span class="eyebrow">PROTECCIÓN DE LA CUENTA</span><h1>Centro de seguridad</h1><p class="muted">Añade una segunda comprobación a tu acceso mediante una aplicación autenticadora.</p>
<div class="grid"><div class="card detail"><span class="icon"><ShieldCheck size={24}/></span><h3>Estado de la sesión</h3><span class:cancelled={!active} class="pill">{active ? 'Segundo factor verificado' : 'Verificación pendiente'}</span><p class="muted small">{data.profile.role==='patient' ? 'El segundo factor es opcional para pacientes.' : 'Necesitas verificarlo para utilizar las funciones del personal.'}</p></div><div class="card detail"><span class="icon"><LockKeyhole size={24}/></span><h3>Permisos</h3><strong>{({patient:'Paciente',doctor:'Médico',reception:'Recepción',admin:'Administración'} as Record<string,string>)[data.profile.role]}</strong><p class="muted small">Solo puedes acceder a la información correspondiente a tu función.</p></div><div class="card detail"><span class="icon"><Smartphone size={24}/></span><h3>Aplicación autenticadora</h3><strong>{enrolled || active ? 'Configurada' : 'Sin configurar'}</strong><p class="muted small">Compatible con aplicaciones de códigos temporales TOTP.</p></div></div>
<section class="card setup"><h2>{active ? 'Protección activada' : enrolled ? 'Verifica tu acceso' : 'Configura el segundo factor'}</h2><p class="muted">{active ? 'Esta sesión completó la verificación adicional.' : enrolled ? 'Abre tu aplicación autenticadora y escribe el código de seis dígitos.' : pending && !qr ? 'Ya hay una configuración pendiente. Si escaneaste su QR, escribe el código. Si perdiste el QR, reinicia la configuración.' : 'Escanea el código QR con una aplicación autenticadora en tu celular.'}</p>{#if message}<div class:success={active} class="alert">{message}</div>{/if}{#if !active}{#if !factorId}<button class="btn" onclick={setup} disabled={busy}>Generar código QR</button>{/if}{#if qr}<div class="qr"><img src={qr.startsWith('data:') ? qr : `data:image/svg+xml;utf8,${encodeURIComponent(qr)}`} alt="Código QR para configurar el segundo factor" /><p class="small muted">Si no puedes escanearlo, escribe este código en tu aplicación:</p><code>{secret}</code></div>{/if}{#if factorId}<form onsubmit={(event)=>{event.preventDefault();verify()}}><div class="field"><label for="totp">Código temporal de 6 dígitos</label><input class="input" id="totp" bind:value={code} inputmode="numeric" autocomplete="one-time-code" oninput={(event)=>{code=event.currentTarget.value.replace(/\D/g,'').slice(0,6);event.currentTarget.value=code}} required placeholder="000000" /></div><button class="btn" disabled={busy}>Verificar código</button></form>{#if pending && !qr}<button class="btn ghost" style="margin-top:12px" onclick={resetPending} disabled={busy}>Perdí el QR · Reiniciar configuración</button>{/if}{/if}{/if}</section>
<style>h1{font-size:2.2rem;margin:7px 0}.grid{margin-top:25px}.detail{box-shadow:none}.detail h3{margin:16px 0 12px}.detail p{margin:15px 0 0}.icon{background:#e9f5ed;color:#27816a;width:44px;height:44px;display:grid;place-items:center;border-radius:12px}.setup{margin-top:22px;max-width:690px}.setup h2{font-size:1.3rem}.setup form{max-width:350px}.qr{margin:20px 0}.qr img{width:170px;max-width:100%;display:block}.qr code{display:block;word-break:break-all;padding:11px;background:#f1f5f2;border-radius:8px}</style>
